FROM node:22.5.1 AS build
RUN mkdir -p /app
ADD  . /app/dify-chat
WORKDIR /app/dify-chat
RUN npm install pnpm -g
RUN pnpm install && \
    pnpm build
FROM nginx:stable AS dist
RUN mkdir /app
COPY --from=build /app/dify-chat/packages/react-app/dist /app/dify-chat/
RUN  chmod -R +r /app/dify-chat/
RUN mkdir -p /usr/share/nginx/html
COPY --from=build /app/dify-chat/packages/react-app/dist /usr/share/nginx/html/dify-chat/
COPY ./nginx_frontend.conf /etc/nginx/conf.d/default.conf
